In [5]:
def fun(lis, a):
    con = 0
    b = len(lis)
    for i in range(b):
        for j in range(i + 1, b):
            if lis[i] + lis[j] == a:
                con += 1
    return con
lis = [2,7,4,1,3,6]
a= 10
result = fun(lis, a )
print("Number of pairs is:", result)


Number of pairs is: 2


In [31]:
import numpy as np

def matr():
    a = int(input("Enter the dimension of the matrix (n x n): "))
    matrix = []
    
    print("Enter the matrix elements row by row:")
    for i in range(a):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        if len(row) != a:
            return "Error: The number of columns does not match the dimension."
        matrix.append(row)
    
    m = int(input("Enter a positive integer m: "))
    if m <= 0:
        return "Error: The integer m must be positive."
    
    if not all(len(row) == a for row in matrix):
        return "Error: The matrix is not square."
    
    matrix_np = np.array(matrix)

    try:
        power = np.linalg.matrix_power(matrix_np, m)
    except np.linalg.LinAlgError as e:
        return f"Error in matrix exponentiation: {e}"
    
    return matrix, matrix_power

result = matr()

if isinstance(result, str):
    print(result)
else:
    matrix, power = result
    print("The matrix is:")
    for row in matrix:
        print(row)
    
    print("Matrix ^ m is:")
    for row in power:
        print(row)


Enter the dimension of the matrix (n x n): 3
Enter the matrix elements row by row:
Row 1: 2 3 4
Row 2: 3 4 5
Row 3: 5 6 7
Enter a positive integer m: 2
The matrix is:
[2.0, 3.0, 4.0]
[3.0, 4.0, 5.0]
[5.0, 6.0, 7.0]
Matrix ^ m is:
[17. 23. 29.]
[24. 33. 42.]
[38. 53. 68.]


In [16]:
def fun(lis):
    if len(lis) < 3:
        print("Range determination not possible")
    mi=min(lis)
    mx=max(lis)
    ran=mx-mi
    return ran
        
lis=[5,3,8,1,0,4]        
result=fun(lis)
print("the range of the list is" , result)

the range of the list is 8


In [35]:
def highest_occurrence(input_string):
    count_dict = {}
    
    for char in input_string:
        if char.isalpha():
            char = char.lower()
            if char in count_dict:
                count_dict[char] += 1
            else:
                count_dict[char] = 1
    
    if not count_dict:
        return "No alphabetic characters found."
    
    highest_char = max(count_dict, key=count_dict.get)
    highest_count = count_dict[highest_char]
    
    return highest_char, highest_count

input_string = input("Enter the string: ")
char, count = highest_occurrence(input_string)
print(f"The highest occurring character is '{char}' with occurrence count {count}.")


Enter the string: hippopotamus
The highest occurring character is 'p' with occurrence count 3.
